services:
  censo:
    #    build: .
    image: harbor.videoatencion.com/library/censo-electoral:latest
    restart: unless-stopped
    environment:
      - TOKEN=12345
      - TIMEZONE=Europe/Madrid
      - DOCUMENT_CHARS=5
      - DAY=true
    volumes:
      - /path/to/my/data:/data
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: '2'
